services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: hexacore
      POSTGRES_PASSWORD: hexacore
      POSTGRES_DB: eventos_emergencias
    ports:
      - '5433:5432'
    volumes:
      - eventos_emergencias_db:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    restart: unless-stopped
    ports:
      - '5672:5672'
      - '15672:15672' # panel de administración: http://localhost:15672 (guest/guest)

volumes:
  eventos_emergencias_db:
